[package]
name = "options-preview-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = "1.0.15"
lazy_static = "1.5.0"
serde = "1.0.216"
tokio = { version = "1.42", features = ["full"] }
warp = "0.3.7"
